### ISSUE TITLE
Extract other information using gwasrapidd

### ISSUE THREAD

**Issue by jiyue1214** [ramiromagno/gwasrapidd#23]
Hi, 

Thanks a lot for developing the package. I am enjoying using the gwasrapidd to extract information from GWAS catalog API. 

Could I know whether I can define other columns to be extracted or only the column in `class?studies`  (for example, besides reported traits in the table, I also want to extract curated traits and background traits like the webpage search result) ?

Thank you for your help
Yue

**Comment by ramiromagno** [comment]
Hi @jiyue1214:

Thank you for your question.

Unfortunately curated traits and background traits retrieval is not yet implemented in gwasrapidd. 

This feature has been recently added to the GWAS Catalog, August this year I believe, and still has to be implemented at the REST API level which gwasrapidd uses to retrieve the data (see the Section API in https://ebispot.github.io/gwas-blog/background-trait-update).

I will try to implement this feature as soon as the GWAS Catalog makes it available at the API level. :)
