### ISSUE TITLE
About failing download the studies of "get_studies()“

### ISSUE THREAD

**Issue by huyou0916** [ramiromagno/gwasrapidd#38]
Professor:
    There is one question I want to  consult. When I input command of "get_sudies()",

> Allstudies <- get_studies()

> Do you still want to proceed (y/n)? y

R.studio return:
"OK! Getting all studies then. This is going to take a while...
  downloading [==>--------------------------------]   8% eta:  4hWarning: The request for https://www.ebi.ac.uk/gwas/rest/api/studies?page=332&size=20 failed: response code was 500.
  downloading [=========================>---------]  74% eta:  1hWarning: The request for https://www.ebi.ac.uk/gwas/rest/api/studies?page=2957&size=20 failed: response code was 500.
  downloading [==============================>----]  89% eta: 23m"

Could you tell me how can I deal with this problem? Looking forward to your reply. Thank you very much.

**Comment by ramiromagno** [comment]
Hi @huyou0916,

`{gwasrapidd}` uses the GWAS Catalog REST API to fetch that data. It does this by iteratively performing multiple HTTP requests. The two 500 errors you got indicate an internal error with the GWAS Catalog server.

I've tried again those URLs that triggered the errors and they seem to be working fine, in isolation. So I guess it might have been a momentary fluke. I'd suggest you try again. Be warned though that fetching all study information in one go will not be the most agile approach. If you really interested in all studies, it might be more practical to download one of the data dumps provided by the GWAS Catalog team: <https://www.ebi.ac.uk/gwas/docs/file-downloads>.

**Comment by huyou0916** [comment]
Thank you for your reply and advice. I have tried to fetch one study and then succeeded.

**Comment by ramiromagno** [comment]
Hi @huyou0916,

Please do let me know if the issue was resolved so that I can close it.

Thanks!

**Comment by huyou0916** [comment]
The problem has been resolved. Thanks a lot!

**Comment by ramiromagno** [comment]
Hi @huyou0916: I would like to reach out by email. Could you send me an email to rmagno at pattern.institute?
