### ISSUE TITLE
Error when running get_associations()

### ISSUE THREAD

**Issue by mightyphil2000** [ramiromagno/gwasrapidd#39]
When running 
gwasrapidd::get_associations(efo_id ="EFO:0001663",verbose = verbose,warnings = warnings) 

I get the following error message:
Error: Elements 1 of is_efo_id2(efo_id) are not true

I wonder what is the cause of the error?

**Comment by mightyphil2000** [comment]
So it actually does work if the efo_id looks like (underscore instead of semicolon)
"EFO_0001663" but not "EFO:0001663"

Is this a bug? Should the script allow semicolons? I got the efo from here:
https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0001663 

Although the url has the underscore in the efo, if you go to the web page the efo has a semicolon and not an underscore.

**Comment by ramiromagno** [comment]
Hi Philip!,

Thank you for taking the time to bring this to my attention.

You are right that `get_associations()` expects an EFO identifier in the format `EFO_0000000`, and should not have a semicolon. It seems both formats are possible. According to this [website](https://ontoma.readthedocs.io/en/stable/), it seems that the format adopted by gwasrapidd is called the _Open Targets JSON schema_. The format using the semicolon is _internal normalised CURIE representation_.

I think it is best to keep it this way as it matches the way the GWAS Catalog uses EFO identifiers:

![snap](https://user-images.githubusercontent.com/19862384/235132062-3cb00a5b-fd3d-4459-b640-ce3ac1bac8ff.png)

**Comment by mightyphil2000** [comment]
Thanks Ramiro! 

Yes agree that makes sense. 

BTW, I should have said colon not semicolon!
