### ISSUE TITLE
How download TSV file like on the web GWAS Catalog？or any function can do like that？ 

### ISSUE THREAD

**Issue by sher-l** [ramiromagno/gwasrapidd#47]
how can I get those?
‘
variant_id      p_value chromosome      base_pair_location      effect_allele   other_allele    effect_allele_frequency odds_ratio      ci_lower        ci_upper        
rs888953847     0.9626  1       594445  T       C       6e-04   0.985   0.522   1.857   -0.0152 0.3236  20301   21839   0       1       chr1:594445:C:T
rs1040232850    0.267   1       595762  CTG     C       0.9986  0.779   0.502   1.210   -0.2494 0.2247  26798   28624   0       0.528   chr1:595762:CTG:C
rs1390538076    0.8214  1       630947  A       G       3e-04   1.102   0.473   2.571   0.0975  0.432   20301   21839   0       1       chr1:630947:G:A
...
’
Thanks.

**Comment by ramiromagno** [comment]
Hello @sher-l ,

Thank you for reaching out.

To help you, can you tell what is the query behind those associations?

**Comment by sher-l** [comment]
> Hello @sher-l ,
> 
> Thank you for reaching out.
> 
> To help you, can you tell what is the query behind those associations? If by study identifier, then look at: #31.

Actually, I need to perform Mendelian randomization analysis using TwoSampleMR, so I need the gwas dataset. Can I get content that can be used for TwoSampleMR through gwasrapidd?

Thank a lot.

**Comment by ramiromagno** [comment]
I am not familiar with the data needed for the R package TwoSampleMR.

For me to write R code that will generate the table you posted above, could you  please share a motivating query so that I can create a self-contained example?

**Comment by sher-l** [comment]
https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90091001-GCST90092000/GCST90091033/GCST90091033_buildGRCh37.tsv.gz

**Comment by ramiromagno** [comment]
Hi @sher-l,

From your messages, I get the feeling you need help on a level beyond the objective usage of gwasrapidd. So the questions raised in this issue might be out of scope. I am happy to help nonetheless --- feel free to contact me by email (my email can be found in this file https://github.com/ramiromagno/gwasrapidd/blob/master/DESCRIPTION).
