### ISSUE TITLE
[Error] response code was 500

### ISSUE THREAD

**Issue by jyjo43043ver1** [ramiromagno/gwasrapidd#49]
Hi,

I am trying to retrieve SNP information using this package, but I encountered a 500 error.

It seems that the GWAS catalog is not properly synchronizing with the package due to GWAS catalog, and I'm unsure how to resolve this.

From previous issues, the suggested solution was to wait for server stabilization.

Is waiting the only option in this case, or is there anything else I can do to resolve the issue?

Thank you.

**Comment by ramiromagno** [comment]
hi @jyjo43043ver1 

Thank you for reporting this! It seems that the GWAS Catalog server is down, indeed.

I have communicated this issue to the gwas catalog team. It should be fixed soon.

**Comment by jyjo43043ver1** [comment]
Dear @ramiromagno 

I checked that the package works perfect! Thanks for your help.

Kind regards
jyjo43043ver1

**Comment by ramiromagno** [comment]
Glad to hear!
