### ISSUE TITLE
Can get_associations search variant_id return Pubmed ID?

### ISSUE THREAD

**Issue by z1242099843** [ramiromagno/gwasrapidd#51]
Hi,
I would like to express my sincere gratitude for developing this package. I have been having a great experience using the gwasrapidd to extract valuable information from the GWAS catalog API.

I want to know whether the get_associations can obtain the pubmed ID when retrieving the variant_id. My intention is to check whether certain sites have been reported in previous literature. 

Like the picture below
![image](https://github.com/user-attachments/assets/787aa439-a7ea-4832-9dc2-f2982d1e5e36)

Could you provide me with some assistance or suggestions on how to extract it from the GWAS catalog? I would be extremely grateful for your help.

**Comment by ramiromagno** [comment]
hi @z1242099843 ,

yes, you can get the Pubmed ID from table `publications`, variable `pubmed_id` when running `get_studies()`. See the cheatsheet https://github.com/rstudio/cheatsheets/blob/main/gwasrapidd.pdf.

Now it all depends on what your starting point is. You can use directly the association identifiers (if that is what you have) and pass them to the `get_studies(association_id = <vector of my association ids>)`. Then just browse the resultant object, as I said earlier, and look at the `publications` table, column `pubmed_id`.

I hope this helps.

**Comment by z1242099843** [comment]
Dear @ramiromagno,

Thank you very much for your reply. 
Following your instructions, I have successfully obtained the information I desired.

**Comment by ramiromagno** [comment]
You're welcome!
