### ISSUE TITLE
Regular expression in function is_study_id no longer works for newest studies

### ISSUE THREAD

**Issue by MattCloward** [ramiromagno/gwasrapidd#9]
Newer studies have ID numbers with more than 6 digits. As of today, October 29, 2020, the highest number of digits in a study ID is 8. However, the regular expression checking whether a string is a study ID or not has 6 as the max number of digits in a study ID. This should be an easy fix, but a more robust workaround may be necessary in the future.

https://github.com/ramiromagno/gwasrapidd/blob/ca5957d98586ee45a098d3d1766df56185f34346/R/parse-utils.R#L241

**Comment by ramiromagno** [comment]
Thank you @MattCloward for reporting this problem.

I will fix it soon.

**Comment by MattCloward** [comment]
Thank you so much! That was lightning fast!

**Comment by ramiromagno** [comment]
You're welcome!
